spring:
  application:
    name: omr_processor
  ai:
    openai:
      base-url: https://integrate.api.nvidia.com
      api-key: ${NVIDIA_API_KEY}
      chat:
        options:
          model: openai/gpt-oss-20b
          temperature: 0.7
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 4200
